// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['jquery', 'underscore', 'deepmodel', 'domReady!', 'common', 'jqueryui', 'jsrender', 'bootstrap', 'jqcookie', 'json2'], function($, _, svc) {
    var headerView, _ref;
    return headerView = (function(_super) {
      __extends(headerView, _super);

      function headerView() {
        _ref = headerView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      headerView.prototype.el = '#header';

      headerView.prototype.tmpUrl = 'template/header.html';

      headerView.prototype.initialize = function() {
        return this.$el.load(this.tmpUrl);
      };

      $.app.header = new headerView();

      return headerView;

    })(Backbone.View);
  });

}).call(this);

/*
//@ sourceMappingURL=header.map
*/
