requirejs.config({
    baseUrl: 'js',
    paths: {
        //jquery          : 'lib/jquery/jquery-1.10.0',
        jquery          : 'lib/jquery/jquery-1.8.3.min',
        //jquery       : 'lib/jquery/jquery-2.0.2',
        jqform          : 'lib/jqform/jquery.form.min',
        qrcode          : 'lib/jquery/jquery.qrcode.min',
        jqcookie        : 'lib/jquery/jquery.cookie',
        jqueryui        : 'lib/jqueryUI/js/jquery-ui-1.10.3.custom.min',
        datepicker_lan  : 'lib/jqueryUI/datepicker_lan/datepicker_lan_tw',
        handsontable    : 'lib/handsontable/jquery.handsontable.full',
        backbone        : 'lib/backbone/backbone',
        deepmodel       : 'lib/backbone/deep-model',
        deepExtend      : 'lib/backbone/underscore.mixin.deepExtend',
        bootstrap       : 'lib/sass-bootstrap/bootstrap/js/bootstrap.min',
        json2           : 'lib/json2/json2',
        underscore      : 'lib/underscore/underscore-min',
        jsrender        : 'lib/jsrender/jsrender',
        cs              : 'lib/require/cs',
        'coffee-script' : 'lib/require/coffee-script',
        domReady        : 'lib/require/domReady',
        common          : 'app/func/common',
        isotope         : 'lib/jquery.isotope/jquery.isotope.min',
        lightbox        : 'lib/lightbox/js/lightbox-2.6.min'
    },
    shim: {
        'underscore'     : {exports:'_'},
        'backbone'       : {deps:['underscore','jquery'], exports:'Backbone'},
        'deepExtend'     : {deps:['underscore']},
        'deepmodel'      : {deps:['backbone','deepExtend']},
        'bootstrap'      : {deps:['jquery']},
        'handsontable'   : {deps:['jquery']},
        'lightbox'       : {deps:['jquery']},
        'jqform'         : {deps:['jquery']},
        'qrcode'         : {deps:['jquery']},
        'isotope'        : {deps:['jquery']},
        'jqueryui'       : {deps:['jquery']},
        'datepicker_lan' : {deps:['jquery','jqueryui']},
        'jsrender'       : {deps:['jquery']},
        'gridster'       : {deps:['jquery']},
        'jqcookie'       : {deps:['jquery']}
    }
});